### ISSUE TITLE
E2E test fails when restarted

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#300]
after deployment, the first test runs through. But a second "make test" leads to an error with pulling actuations:
1) Creating and getting components ... 

       Shall get list of actuations:
     Error: get list of actuations: {"code":500,"status":500,"message":"Internal Server Error"}

This is reproducible. First investigation reveals that if DB does not contain only one device, it works, with several devices from different accounts it fails. I suspect that this is a regression introduced when we moved to unique device UUIDs independent of accounts.

**Comment by oguzcankirmemis** [comment]
Actuation bug is somehow not related to this problem. Here is why: If the tests pass for the first time, theoretically it removes everything it has created in the last step, which means database should be 'fresh' and the tests should pass second time as well (because there is simply nothing in db). If the tests fail for some other reason and old devices/components still exist, then the actuation test fails because of the bug fixed at frontend PR [#201](https://github.com/Open-IoT-Service-Platform/oisp-frontend/pull/201).

Then I realized the other problem, the first failing test at second time is not the actuations, rather:

`  1) Sending observations and checking rules ...

       Shall send observation and check rules:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
`
I have also looked into this but could not find the reason. Frontend/Websocket logs were completely fine. @wagmarcel could you verify, whether it is something that only happens by me or not.

**Comment by wagmarcel** [comment]
in my case I noted that the actuation cannot be pulled the 2nd time. but it is there. So in the actuation test, this actuation is there and confuse the test (because the test is sending data and wait for the *right* actuation. But with the first actuation it gets totally confused and waits for the right actuation forever.

**Comment by oguzcankirmemis** [comment]
Yes, this makes perfect sense. I was trying to say that the mentioned PR in frontend does fix the actuation problem, meaning shall get list of actuations test does not fail anymore, but e2e tests overall still do fail (at least by me) when sending observations for no obvious reason.
