### ISSUE TITLE
Fix log4j for Kafka

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#561]

**Comment by oguzcankirmemis** [comment]
Kafka uses log4j version 1.2.17, and thus is not affected by the vulnerabilities in 2.x. However, it is impacted by the CVE-2021-45046. Since JMSAppender is not configured by default, it is nevertheless still safe. We still need to update Kafka though, just to be completely safe from the vulnerability.

As a side note, the current Kafka chart (incubator@kafka) we are using is archived and does no longer receive updates.

https://kafka.apache.org/cve-list - Section: CVE-2021-45046 and CVE-2021-4104
